export const GET_STREAM = 'GET_STREAM';
export const KILL_STREAM = 'KILL_STREAM';
export const START_DETECTION = 'START_DETECTION';
export const STOP_DETECTION = 'STOP_DETECTION';
export const GET_ERRORS = 'GET_ERRORS';
export const GET_PATTERNSTAMP = 'GET_PATTERNSTAMP';
export const GET_NODE_HEALTHSTATUS = 'GET_NODE_HEALTHSTATUS';
export const GET_FLASK_HEALTHSTATUS = 'GET_FLASK_HEALTHSTATUS';
